language: generic 
sudo: required

before_install:
  - docker buils -t emanuelemiucci/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true USERNAME/react-test npm test

after_success:
  - docker build -t emanuelemiucci/multi-client ./client
  - docker build -t emanuelemiucci/multi-nginx ./nginx
  - docker build -t emanuelemiucci/multi-server ./server
  - docker build -t emanuelemiucci/multi-worker ./worker
#Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
#Take those images and push them to docker hub
  - docker push emanuelemiucci/multi-client
  - docker push emanuelemiucci/multi-nginx
  - docker push emanuelemiucci/multi-server
  - docker push emanuelemiucci/multi-worker
